# CONNECTION
SIZE_OF_DATA = 1024
MAX_LISTEN = 5

# PLAYER - config
NUM_OF_TRIES = 3
MAX_INPUT_LEN = 50
KICK_TIME = 10.0
IGNORE_TIME = 5.0   # TODO: zmienić na 2.0

# HASH PASSWORD
SALT = b'12'
HASH_METHOD = 'sha256'
ITERATIONS = 1000

# REGISTER & LOGIN
LOGIN_REGISTER_TABLE = 'databases/users'
USERNAME_MAX_LEN = 20
PASSWORD_MAX_LEN = 100

# GAME
LETTERS_1LINE = 'weęruioóaąszżźxcćvnńm'
LETTERS_2LINE = 'pyjgq'
LETTERS_3LINE = 'tlłbdhk'
LETTERS_4LINE = 'f'
ALPHABET = LETTERS_1LINE + LETTERS_2LINE + LETTERS_3LINE + LETTERS_4LINE
DIGITS = '0123456789'
DICT_PATH = 'static/resources/slowa.txt'
GUESS_WORD_POINTS = 5
GUESS_LETTER_POINTS = 1
GAME_HISTORY_TABLE = 'databases/game_history'
MAX_PLAYERS = 10
MIN_PLAYERS = 2
MAX_GUESSES = 10
MAX_QUEUE_TIME = 50     # TODO: change to 5 * 60
